[workspace]
members = [
    "rsky-relay",
    "rsky-common",
    "rsky-identity",
]
default-members = ["rsky-relay"]
resolver = "2"

[workspace.dependencies]
rsky-common = { path = "rsky-common" }
rsky-identity = { path = "rsky-identity" }
